### ISSUE TITLE
ウェイトリストの自動更新がされなくなる

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#12]
しばらくは自動更新されるがされなくなるらしい
Chromeで発生するみたい
おそらく別タブにしているときにJSが一時凍結される？弊害

/cc @azutake

**Comment by ingen084** [comment]
#7 の再接続で対応できるかもしれないけど他の不具合かもしれないので。

**Comment by azutake** [comment]
再生中のやつ表示しようとしたら、例外で切断され一緒に情報が送られてくるウェイトリストもバグってたみたい
修正しました
