### ISSUE TITLE
リクエストしていないのがリクエストしたことになる問題

### ISSUE THREAD

**Issue by azutake** [Gletec/NecosenFeedback#16]

**Comment by ingen084** [comment]
暫定修正 確認できれば閉じます

**Comment by ingen084** [comment]
Web側でリクエストすると問題が発生する模様?詳細は検証待ち

**Comment by azutake** [comment]
とりあえず暫定的に修正してみた。これから検証

**Comment by azutake** [comment]
**問題点**

Web側からリクエストすると、何故か VideoId だけが更新されずに保存されている可能性がある

**Comment by azutake** [comment]
**暫定修正**

バックエンドに一度渡してからリクエスト処理実施

そのうち根本的な原因探ります
