### ISSUE TITLE
現在再生中の動画の文字を少し小さくしてほしい

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#18]
流石にユーザー名が長いとやばいことになるので。
どうしても小さくできない場合はユーザー名以外の部分を少し小さくしてほしい

**Comment by SnO2WMaN** [comment]
実質#17と同じような内容なのでIssue閉じてもいいと思う

**Comment by azutake** [comment]
いや小さくしてほしいだから重複じゃなくね

**Comment by ingen084** [comment]
連携ページ新装に伴いClose
