### ISSUE TITLE
[バックエンド側]スキップ処理

### ISSUE THREAD

**Issue by azutake** [Gletec/NecosenFeedback#22]
データベース側に、スキップリクエストしたユーザを一時保管するテーブルが欲しい
これは、フロントエンド側が複数に分散した際に、ユーザの整合性を取るため。

**Comment by azutake** [comment]
**要件**

1. ユーザID
2. シグネチャ(tohoとかそういう)

再生開始のタイミングで、スキップ処理のテーブル内クリアに出来たら嬉しいけど、OSMでの地獄を見た後だから、挿入だけして、スキップしたらIsSkippedフラグ立てるなりしてから、定期的に削除とかの方がいいかもしれない。

**Comment by ingen084** [comment]
了解 詳細については後ほど。

**Comment by azutake** [comment]
Redisで実装
