### ISSUE TITLE
上部ニュース欄に長い文字を入力すると横に伸びまくる

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#24]
スクロールした方がいいと思う
![サンプル](http://gyazo.ingen084.net/data/c652d548400c49faa01a21d232cdba8a.png "yome")

**Comment by SnO2WMaN** [comment]
長い文字を入力するのもどうかと思う

**Comment by azutake** [comment]
そういう問題じゃない

**Comment by azutake** [comment]
通知するにあたって普通に文字数越すことは十分にありえる

**Comment by ingen084** [comment]
そもそもここで普通に通知できる長さだったら放送主コメントだけで間に合ってると思うんですけど（極論

**Comment by SnO2WMaN** [comment]
そもそも何を通知するのここ

**Comment by ingen084** [comment]
将来的に同様の処理で当選情報とか発言するところだと思っておいてくれれば

**Comment by SnO2WMaN** [comment]
それモーダルウィンドウ的な感じでやっていかんかね

スクロールバーHTML構造変えないと無理そう

**Comment by azutake** [comment]
ダメです

**Comment by azutake** [comment]
そもそも、１回限りではないし、ちょっとした通知にも使われる場所だから

**Comment by SnO2WMaN** [comment]
ガッシャーン

**Comment by SnO2WMaN** [comment]
修正したと思う

**Comment by azutake** [comment]
site.css編集するのやめよう
