### ISSUE TITLE
DB更新系Issueまとめ

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#25]
#22 スキップ処理 すでにSRを送っているかの判定用
#23 GoodRequest 最後にGood判定用
#14 運営タイム 別テーブル化
#10 枠取り関係 多分DBで管理したほうが良さげ

**Comment by azutake** [comment]
#23 はフロントエンドで集計して、結果だけをDBに書き込むってのは有り？無し？(現状のGoodCount カラム使うとして)

**Comment by ingen084** [comment]
アリだと思う、むしろそっちのがいいと思います

**Comment by ingen084** [comment]
枠取り以外完成してるのでClose
