### ISSUE TITLE
デプロイ中画面作れない？

### ISSUE THREAD

**Issue by azutake** [Gletec/NecosenFeedback#26]
IISでデプロイ中に表示される画面
HTML, js, css 含めて512kb　以内(app_offline-template.htm 単一ファイル)

**Comment by SnO2WMaN** [comment]
これは.html内にcssとjavascript書けって事でOK？

**Comment by azutake** [comment]
ｋ

**Comment by azutake** [comment]
MSDeployでしばらく代用
