### ISSUE TITLE
「認証しました」のデザイン

### ISSUE THREAD

**Issue by SnO2WMaN** [Gletec/NecosenFeedback#27]
![chrome_2017-05-23_21-22-06](https://cloud.githubusercontent.com/assets/15155608/26354049/f21e406a-3ffd-11e7-8556-d6b086190f4a.png)

直す

**Comment by ingen084** [comment]
正直認証したら消してもいいと思う

**Comment by azutake** [comment]
認証したら消すのもいいし、最小限のスペースで認証解除する場所が欲しい

**Comment by azutake** [comment]
「認証中…」系も欲しかったりする

**Comment by azutake** [comment]
@SnO2WMaN 現状の「認証済み」のヤツ、認証中はアイコンの部分（又は円のボーダ部分）で　くるくる回ってる感じのアニメーションって付けられないかな
