### ISSUE TITLE
ニュース欄を増やす

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#33]
生放送画面の下ぐらいに(見やすいように)ニュース(と同じような場所)を実装する。主に当選通知など用。
タイトルは別になしでいいので、スクロールするメッセージを表示できるようにする。

詳細な位置などは今後検討

**Comment by azutake** [comment]
上はいじれても下はいじれないと思う。
それこそ position: fixedで右下に表示するぐらいしかないんじゃないの

**Comment by azutake** [comment]
認証が使えるようになれば、コメントによるリク切れる(or リク結果非表示に出来る)のにね

**Comment by ingen084** [comment]
リクエストの上かNECOちゃんの横に持っていきたい感じではある

**Comment by azutake** [comment]
良いと思う。 これ前に、例のあっこで話に出た吹き出しでやるってのもアリだね

**Comment by azutake** [comment]
ってことで @SnO2WMaN デザインよろ

**Comment by ingen084** [comment]
ついでに、画面幅より狭い文字を表示させようとしたときにもスクロールしてしまうのを修正してほしい

**Comment by SnO2WMaN** [comment]
![2017-06-03_22-56-46](https://cloud.githubusercontent.com/assets/15155608/26754150/f291239a-48af-11e7-83c8-55ef98d8a92b.gif)

なんのことを言っているのか分からなかったがどうも移植ミスであったことが判明した

**Comment by SnO2WMaN** [comment]
@azutake 修正頼んだ(丸投げ)
