### ISSUE TITLE
認証解除ボタン

### ISSUE THREAD

**Issue by azutake** [Gletec/NecosenFeedback#34]
認証済みの場合、ユーザ名やらが表示されている所をホバーすると、名前などの代わりに「認証解除」と出すようにしてほしい

/cc @SnO2WMaN

**Comment by SnO2WMaN** [comment]
そもそもホバーで表示させるくらいなら最初から表示したほうがいいんじゃないかなぁ(逃げ)

**Comment by azutake** [comment]
最初から表示できるようなスペースどこにあるの
