### ISSUE TITLE
「認証に失敗しました」モーダル

### ISSUE THREAD

**Issue by azutake** [Gletec/NecosenFeedback#35]
OAuth実装に向けて、認証処理に失敗した(必須スコープが無い、認証拒否した等)場合に表示する

モーダル構成

**niconicoとの連携に失敗しました**
スコープ user が許可されていません

みたいな感じで。
本件は出来る限りなるはやで頼んだ

**Comment by SnO2WMaN** [comment]
![code_2017-06-03_00-15-57](https://cloud.githubusercontent.com/assets/15155608/26732909/3200092c-47f4-11e7-9acd-3b4aa26160c9.png)
![chrome_2017-06-03_00-16-10](https://cloud.githubusercontent.com/assets/15155608/26732910/321d437a-47f4-11e7-8ea8-5b8960cb49ee.png)

こんな感じで

**Comment by SnO2WMaN** [comment]
これは閉じていいと思う(クソ適当)

**Comment by azutake** [comment]
OAuth実装まで何があるかわからないので保留
