### ISSUE TITLE
バグ報告&要望(つまりここ)へのリンク

### ISSUE THREAD

**Issue by SnO2WMaN** [Gletec/NecosenFeedback#36]
どっかに作ったほうがいいんじゃない？

**Comment by azutake** [comment]
考え中、フッターのどこかあたりに通常リンクとして設置しても良さそうだなぁとは思う

**Comment by ingen084** [comment]
まだバグ多いし上部のチャンネルページへのリンクに近づけたほうがわかりやすい気もする

**Comment by azutake** [comment]
無理じゃね＆邪魔

**Comment by ingen084** [comment]
がんばって

**Comment by ingen084** [comment]
寧ろページ下部とかのわかりづらい場所だとあんまり変わらない気がする

**Comment by azutake** [comment]
あるのと無いのとじゃ案内のしやすさ的な違うはある

**Comment by azutake** [comment]
というか、上部は無理でしょ、「NECOSen」の文字の横に置くぐらしか

**Comment by azutake** [comment]
まぁ私はやらないけど

**Comment by ingen084** [comment]
くそでかい[チャンネル]ボタンの近くに配置するぐらいじゃないといちいち案内してもらえないときづけないのはよろしくないかと @SnO2WMaN がんばって

**Comment by azutake** [comment]
小さくしてもアイコン１個表示するのがやっとだと思うけど

**Comment by ingen084** [comment]
それでもぜんぜん違うと思うよ！

**Comment by azutake** [comment]
ページ下部に追加済み
