### ISSUE TITLE
ボタンが押せなくなる

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#37]
タグ部分の文字が長くなるとボタン群が改行してしまいボタンが押せなくなる環境がある(スクショ欲しかったらその時探す)
/cc @SnO2WMaN

**Comment by SnO2WMaN** [comment]
![chrome_2017-06-05_20-56-14](https://cloud.githubusercontent.com/assets/15155608/26783109/6fd20fae-4a31-11e7-977b-eff16bd8129e.png)

**Comment by ingen084** [comment]
![5000兆円](http://gyazo.ingen084.net/data/5b213c3047b5d3ad67c1a9acc35b48c0.png "5000兆円")

**Comment by azutake** [comment]
@SnO2WMaN まだ？

**Comment by ingen084** [comment]
@SnO2WMaN まだ？

**Comment by SnO2WMaN** [comment]
![chrome_2017-08-13_01-17-35](https://user-images.githubusercontent.com/15155608/29242340-539ef39a-7fc6-11e7-96a9-a8606aad44e8.png)

こうか
