### ISSUE TITLE
リクエスト倍率の表示

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#38]
## 現在の件数表示の改訂版
すべて仮
凡例: 表記名(リクエスト待ち件数)

枯渇(-5)
枯渇気味(6-9)
快適(10-19)
普通(20-39)
混雑(40-99)
すごく混雑(100-)

デザイン的にかなりつらそう(バックエンド担当並の感想)

**Comment by ingen084** [comment]
枯渇気味っていうのはちょっとアレなんで快適に取り込むという案もあります

**Comment by ingen084** [comment]
表記は場所がないため廃止、混雑度によって抽選まであと○曲の左側のバーの色を変更するようにする
@SnO2WMaN よろしく

**Comment by SnO2WMaN** [comment]
英語調べるのがめんどくさかったので

快適(10-19) -> Local

普通(20-39) -> Express

混雑(40-99) -> Limitted Express

すごく混雑(100-) -> Rapid Limitted Express

とした

**Comment by SnO2WMaN** [comment]
混雑のほうが快速特急だったりするけどもう知らん

**Comment by azutake** [comment]
さすがに命名がクソなのであとで直します
