### ISSUE TITLE
マイリストからのリクエストデザイン

### ISSUE THREAD

**Issue by azutake** [Gletec/NecosenFeedback#41]
* マイリストからのリクエストを　リクエストフォームの下に追加
* これに伴い、「マイリスから」「検索から」「過去リクエストから」のヤツをトグルで扱えるようにして(要するにチェック済みの場合のデザイン作って)

**Comment by azutake** [comment]
![SS](http://gyazo.ingen084.net/data/881b46233603ae126bb70e777828775d.png)

こんな感じで

**Comment by SnO2WMaN** [comment]
とてもわかりやすい仕様書 👍 👍 👍 🎉 🎉 🎉

**Comment by ingen084** [comment]
仕様書ではないな…

**Comment by SnO2WMaN** [comment]
「マイリスから」は終わったので
「検索から」の仕様書
![1](https://user-images.githubusercontent.com/15155608/27010510-56985606-4ee1-11e7-95e9-7482f18f0d51.png)

**Comment by azutake** [comment]
それよりも左のリストもうちょっとなんとかして

**Comment by azutake** [comment]
マイリストからのリクエスト　API

/api/v1/Video/MyList/User/ ;自身のマイリスト一覧(ID, マイリス名) [RequireAuthorized]
/api/v1/Video/MyList/User/2 ;指定したユーザ(2)のマイリスト取得
/api/v1/Video/MyList/1111 ;指定したマイリストを取得
