### ISSUE TITLE
[内部構造]多チャンネル配信に対応させる

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#50]
### 主な作業
signature用テーブルの作成
各項目にsignatureを追記する
Usersテーブルの親子関係を変更する

**Comment by azutake** [comment]
# フロントエンド側

- [x] 各シグネチャに対する説明文、リクエスト可否設定を指定できるようにする

**Comment by azutake** [comment]
Front-end is already support multiple channels.

**Comment by azutake** [comment]
間違えて閉じてしまった
