### ISSUE TITLE
その動画が最後に流れた時間などをマイリスからリクの画面などに表示する

### ISSUE THREAD

**Issue by ingen084** [Gletec/NecosenFeedback#69]
サムネイル付近などに小さく表示するのが望ましい

- `3分前`や`4時間前`のような表記、ツールチップで解説と詳細な日付
- クールタイム中でリクエストできない場合はアイコンなど表示しクールタイム中でリクエストできないことを示す(別にクリック無効化などの処理は必要ない

機能追加等に直結する内容のため**デザインの期日は10月10日前後を予定**

**Comment by ingen084** [comment]
## 詳細
### 種類
大きく分けて3種
- クールタイム期間中でリクエストができない
- 普通にリクエストが可能(以前に流れた時間表示あり)  
時間の表示方法は『◯時間前』『◯日前』『○ヶ月前』『半年以上前』などを想定
  - それ以外の表示はなし
  - 当選率が下がるアイコンを追加で表示
- 普通にリクエストが可能(以前に流れた時間表示なし)

各項目は文字以外はアイコンのほうがわかりやすい？
ツールチップ有りで、JS側から編集ができるものとする

### 場所
現状では
- リクエスト中の動画が表示される画面
- マイリストからリクエストの画面
- 過去リク・検索からリクエストの画面(予定)

サムネイルにかぶせたらわかりやすいかなーと思ったけどそれよりもわかりやすいと思った方式があればそれでもおｋ
汎用的にどうぞ

**Comment by SnO2WMaN** [comment]
.thumbnail_wrap要素に「.cooltime」クラスを付けると、クールタイムとして

![chrome_2017-10-09_02-26-06](https://user-images.githubusercontent.com/15155608/31319435-65906e80-ac9e-11e7-99c4-5a865bd87b8c.png)

こうなります。

時間表示のときはこのコードをthumbnail_wrap要素直下に置いてください。
```
<div class="info_wrap">
　<i class="material-icons">trending_down</i>
　<p class="text">9時間前</p>
</div>
```
クールタイム中は消えようCSS側で設定しています。

**追記**
　マイリストのサムネにもリンクを設定しておきました。

**Comment by SnO2WMaN** [comment]
**追記**

.video_wrap要素に.cooltimeを付けてくれ

**Comment by SnO2WMaN** [comment]
ツールチップなんですが、.video_wrap要素にtitle属性を付けてくれれば実現するのでそこは頼んだ(投げやり)

**Comment by ingen084** [comment]
新連携ページにて本格実装なのでClose
